index:
    path: /
    controller: App\Controller\HomeController::index
app_task_tables:
    path: /task/tables
    controller: App\Controller\TaskTablesController::index
app_task_tables_create:
    path: /task/tables/create
    controller: App\Controller\TaskTablesController::create

table_new:
    path: /api
    methods: [POST]
    controller: App\Controller\ApiController::new
user_registration:
    path: /register
    methods: [POST]
    controller: App\Controller\RegistrationController::register