index:
    path: /
    controller: App\Controller\HomeController::index
app_task_tables:
    path: /task/tables
    controller: App\Controller\TaskTablesController::index
app_task_tables_create:
    path: /task/tables/create
    controller: App\Controller\TaskTablesController::create



user_registration:
    path: /register
    methods: [POST]
    controller: App\Controller\RegistrationController::register
app_api_login:
    path: /api/login
    methods: [ POST ]
    controller: App\Controller\ApiLoginController::index

#Tables action

table_new:
    path: /api/table/add
    methods: [POST]
    controller: App\Controller\ApiController::new
table_team_index:
    path: /api/teamtables
    methods: [POST]
    controller: App\Controller\ApiController::teamTables
table_index:
    path: /api/tables
    methods: [ POST ]
    controller: App\Controller\ApiController::index

table_show:
    path: /api/table/{id}
    methods: [ POST ]
    controller: App\Controller\ApiController::showTab

table_update:
    path: /api/table/{id}/update
    methods: [ POST ]
    controller: App\Controller\ApiController::updateTab

table_add_user:
    path: /api/table/{id}/user/add
    methods: [ POST ]
    controller: App\Controller\ApiController::addUserToTab

table_team:
    path: /api/table/{id}/team
    methods: [ POST ]
    controller: App\Controller\ApiController::getTeammatesTable

table_remove_user:
    path: /api/table/{id}/user/remove
    methods: [ POST ]
    controller: App\Controller\ApiController::removeUserToTab
#Tasks

table_task_add:
    path: /api/table/{id}/task/add
    methods: [ POST ]
    controller: App\Controller\ApiController::taskAdd

table_tasks_get_all:
    path: /api/table/{id}/tasks
    methods: [ POST ]
    controller: App\Controller\ApiController::tasksGetAll

task_remove:
    path: /api/table/{id}/task/remove
    methods: [ POST ]
    controller: App\Controller\ApiController::removeTask

#Columns
column_new:
    path: /api/table/{id}/column/add
    methods: [ POST ]
    controller: App\Controller\ApiController::addColumn

table_columns_get_all:
    path: /api/table/{id}/columns
    methods: [ POST ]
    controller: App\Controller\ApiController::columnGetAll

column_remove:
    path: /api/table/{id}/column/remove
    methods: [ POST ]
    controller: App\Controller\ApiController::removeColumn

#Comments

comment_new:
    path: /api/table/{id}/comment/add
    methods: [ POST ]
    controller: App\Controller\ApiController::addComment

comment_remove:
    path: /api/table/{id}/comment/remove
    methods: [ POST ]
    controller: App\Controller\ApiController::removeComment

comments_get_all:
    path: /api/table/{id}/comments
    methods: [ POST ]
    controller: App\Controller\ApiController::commentsGetAll

#Timer
timer_new:
    path: /timer/task/{id}/add
    methods: [ POST ]
    controller: App\Controller\TimersController::addTimer

timer_remove:
    path: /timer/{id}/remove
    methods: [ POST ]
    controller: App\Controller\TimersController::removeTimer

timer_get_all:
    path: /timer/task/{id}
    methods: [ POST ]
    controller: App\Controller\TimersController::index

timer_user_get_all:
    path: /timer/user/{id}
    methods: [ POST ]
    controller: App\Controller\TimersController::getTimersUser

#Files
file_comment_new:
    path: /file/task/{id}/add
    methods: [ POST ]
    controller: App\Controller\FilesController::addFile

file_comment_remove:
    path: /file/task/{id}/remove
    methods: [ POST ]
    controller: App\Controller\FilesController::removeFile